---
version: "3.8"
services:
  gitlab:
    image: registry:2
    container_name: docker-registry
    restart: unless-stopped
    ports:
      - 0.0.0.0:9004:5000
    volumes:
      - /opt/ablack/docker-registry:/var/lib/registry

